# Generated by Django 5.2.17 on 2026-08-17 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0005_curriculumtopic_learningplan_topicmilestone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=240)),
                ('tagline', models.CharField(blank=True, default='', help_text='Short one-line architectural summary', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='', max_length=400)),
                ('live_demo_url', models.URLField(blank=True, default='', max_length=400)),
                ('primary_language', models.CharField(blank=True, default='Python', max_length=100)),
                ('technologies', models.JSONField(blank=True, default=list, help_text="List of tech tags e.g. ['Django', 'React', 'PostgreSQL']")),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('MAINTENANCE', 'Maintenance'), ('ARCHIVED', 'Archived')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private (Only Me)'), ('COMMUNITY', 'Community Developers'), ('PUBLIC', 'Public on Portfolio')], db_index=True, default='PUBLIC', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text="Featured on developer's personal portfolio")),
                ('is_showcase', models.BooleanField(db_index=True, default=False, help_text='Promoted to global Navapai community showcase')),
                ('github_repo_id', models.BigIntegerField(blank=True, null=True)),
                ('github_owner', models.CharField(blank=True, default='', max_length=100)),
                ('github_repo_name', models.CharField(blank=True, default='', max_length=100)),
                ('github_stars_count', models.PositiveIntegerField(default=0)),
                ('github_forks_count', models.PositiveIntegerField(default=0)),
                ('github_open_issues', models.PositiveIntegerField(default=0)),
                ('github_default_branch', models.CharField(default='main', max_length=50)),
                ('github_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('github_metadata', models.JSONField(blank=True, default=dict, help_text='Full repository metadata, topics, license, language breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community_domain', models.ForeignKey(blank=True, help_text='Canonical community domain category (e.g. Django, AWS).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_projects', to='domains.communitydomain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('user_domain', models.ForeignKey(blank=True, help_text="Link to developer's enrolled domain workspace.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='domains.userdomain')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Screenshot',
                'verbose_name_plural': 'Project Screenshots',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['visibility', 'is_showcase'], name='projects_pr_visibil_21ae5b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'status'], name='projects_pr_user_id_40c3f7_idx'),
        ),
    ]
