# Generated by Django 5.2.17 on 2026-08-18 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(help_text='Markdown formatted contribution guide.')),
                ('category', models.CharField(choices=[('GUIDE', 'Technical Guide / Tutorial'), ('BLUEPRINT', 'Architecture Blueprint'), ('INTERVIEW_PREP', 'Interview Prep & Q&A'), ('BEST_PRACTICES', 'Production Best Practices'), ('BUG_FIX', 'Troubleshooting & Bug Fix')], db_index=True, default='GUIDE', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Moderation Review'), ('APPROVED', 'Approved & Published'), ('REJECTED', 'Needs Revisions / Rejected')], db_index=True, default='APPROVED', max_length=20)),
                ('upvotes_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contributions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Contribution',
                'verbose_name_plural': 'Community Contributions',
                'ordering': ['-upvotes_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='community.communitycontribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution Upvote',
                'verbose_name_plural': 'Contribution Upvotes',
                'unique_together': {('user', 'contribution')},
            },
        ),
    ]
