# Generated by Django 5.2.17 on 2026-08-18 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('company_or_org', models.CharField(blank=True, default='', max_length=255)),
                ('milestone_type', models.CharField(choices=[('JOB', 'New Job / Role'), ('PROMOTION', 'Promotion'), ('CERTIFICATION', 'Certification Earned'), ('PROJECT_LAUNCH', 'Project Launch'), ('OPEN_SOURCE', 'Open Source Milestone'), ('SPEAKER', 'Tech Talk / Speaker'), ('OTHER', 'General Milestone')], db_index=True, default='JOB', max_length=30)),
                ('date_achieved', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Milestone',
                'verbose_name_plural': 'Career Milestones',
                'ordering': ['-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, default='', max_length=255)),
                ('credential_url', models.URLField(blank=True, default='', max_length=500)),
                ('badge_icon_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_verified', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date'],
            },
        ),
    ]
