# Generated by Django 5.2.17 on 2026-08-18 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0005_curriculumtopic_learningplan_topicmilestone_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(help_text='Markdown formatted notes and explanations.')),
                ('code_snippet', models.TextField(blank=True, default='', help_text='Optional raw code snippet.')),
                ('programming_language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('sql', 'SQL'), ('bash', 'Bash / Shell'), ('dockerfile', 'Dockerfile'), ('yaml', 'YAML / Config'), ('json', 'JSON'), ('markdown', 'Markdown'), ('plaintext', 'Plain Text')], db_index=True, default='python', max_length=50)),
                ('tags', models.CharField(blank=True, default='', help_text="Comma-separated tags e.g. 'jwt, postgres, auth'", max_length=255)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_notes', to=settings.AUTH_USER_MODEL)),
                ('user_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='domains.userdomain')),
            ],
            options={
                'verbose_name': 'Developer Note',
                'verbose_name_plural': 'Developer Notes',
                'ordering': ['-is_pinned', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_pinned'], name='notes_devel_user_id_1fd89e_idx'), models.Index(fields=['is_public'], name='notes_devel_is_publ_ccd9a6_idx')],
            },
        ),
    ]
