# Generated by Django 5.2.17 on 2026-08-18 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0005_curriculumtopic_learningplan_topicmilestone_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], db_index=True, default='TODO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('category', models.CharField(choices=[('LEARNING', 'Learning & Theory'), ('CODING', 'Coding & Dev'), ('ARCHITECTURE', 'Architecture & Design'), ('REVIEW', 'Code Review & Refactoring'), ('OTHER', 'General / Other')], db_index=True, default='LEARNING', max_length=25)),
                ('week_number', models.PositiveIntegerField(db_index=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=60, help_text='Estimated completion time in minutes')),
                ('actual_minutes', models.PositiveIntegerField(default=0, help_text='Actual time spent in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text="Optional link to developer's portfolio project.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to=settings.AUTH_USER_MODEL)),
                ('user_domain', models.ForeignKey(blank=True, help_text="Optional link to user's enrolled domain workspace.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='domains.userdomain')),
            ],
            options={
                'verbose_name': 'Weekly Task',
                'verbose_name_plural': 'Weekly Tasks',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.weeklytask')),
            ],
            options={
                'verbose_name': 'Sub Task',
                'verbose_name_plural': 'Sub Tasks',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklytask',
            index=models.Index(fields=['user', 'year', 'week_number'], name='tasks_weekl_user_id_83a2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklytask',
            index=models.Index(fields=['user', 'status'], name='tasks_weekl_user_id_cd3872_idx'),
        ),
    ]
