# Generated by Django 5.2.17 on 2026-08-18 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Award', help_text="Lucide Icon Name e.g. 'Award', 'Zap', 'ShieldCheck'", max_length=50)),
                ('category', models.CharField(choices=[('LEARNING', 'Domain Learning & Plans'), ('PROJECTS', 'Projects & GitHub'), ('TASKS', 'Weekly Tasks & To-Dos'), ('NOTES', 'Developer Notes'), ('RESOURCES', 'Bookmarks & Library'), ('CAREER', 'Certifications & Milestones'), ('COMMUNITY', 'Community & Showcase')], db_index=True, default='LEARNING', max_length=30)),
                ('points_reward', models.PositiveIntegerField(default=50, help_text='XP awarded when unlocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Achievement Badge',
                'verbose_name_plural': 'Achievement Badges',
                'ordering': ['category', 'points_reward', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='gamification.achievementbadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
