# Generated by Django 5.2.17 on 2026-08-18 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=500)),
                ('resource_type', models.CharField(choices=[('DOCUMENTATION', 'Official Documentation'), ('VIDEO', 'Video & Screencast'), ('ARTICLE', 'Article / Guide'), ('BOOK', 'Book / E-Book'), ('COURSE', 'Interactive Course'), ('TOOL', 'Dev Tool / Library'), ('GITHUB_REPO', 'GitHub Repository'), ('OTHER', 'Other Resource')], db_index=True, default='DOCUMENTATION', max_length=30)),
                ('category', models.CharField(db_index=True, help_text="e.g. 'Cloud', 'Frontend', 'Database'", max_length=100)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('ALL_LEVELS', 'All Levels')], db_index=True, default='ALL_LEVELS', max_length=20)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('author_or_creator', models.CharField(blank=True, default='', max_length=150)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Learning Resource',
                'verbose_name_plural': 'Learning Resources',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_notes', models.TextField(blank=True, default='', help_text="User's personal notes on this resource")),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Resource Bookmark',
                'verbose_name_plural': 'Resource Bookmarks',
                'ordering': ['-is_favorite', '-created_at'],
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
