# Generated by Django 5.2.17 on 2026-08-15 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('normalized_title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(db_index=True, default='Software Engineering', max_length=100)),
                ('icon_name', models.CharField(blank=True, default='code', max_length=50)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_approved', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], db_index=True, default='APPROVED', max_length=20)),
                ('members_count', models.PositiveIntegerField(default=0)),
                ('topics_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Null indicates core system/platform seeded domain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_community_domains', to=settings.AUTH_USER_MODEL)),
                ('parent_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdomains', to='domains.communitydomain')),
            ],
            options={
                'verbose_name': 'Community Domain',
                'verbose_name_plural': 'Community Domains',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DomainAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('normalized_alias', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='domains.communitydomain')),
            ],
            options={
                'verbose_name': 'Domain Alias',
                'verbose_name_plural': 'Domain Aliases',
            },
        ),
        migrations.AddIndex(
            model_name='communitydomain',
            index=models.Index(fields=['slug', 'is_approved', 'is_public'], name='domains_com_slug_bc0c67_idx'),
        ),
        migrations.AddIndex(
            model_name='communitydomain',
            index=models.Index(fields=['category', 'is_approved'], name='domains_com_categor_2b1b66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domainalias',
            unique_together={('domain', 'alias')},
        ),
    ]
