# Generated by Django 5.2.17 on 2026-08-16 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_domain', models.CharField(help_text='Original topic or domain name requested to merge', max_length=200)),
                ('similarity_score', models.FloatField(default=0.0, help_text='PostgreSQL trigram similarity percentage (e.g., 0.94 for 94%)')),
                ('reason', models.TextField(blank=True, default='')),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('final_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_merge_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_merge_requests', to=settings.AUTH_USER_MODEL)),
                ('target_domain', models.ForeignKey(help_text='Canonical target domain', on_delete=django.db.models.deletion.CASCADE, related_name='merge_logs', to='domains.communitydomain')),
            ],
            options={
                'verbose_name': 'Domain Merge Audit Log',
                'verbose_name_plural': 'Domain Merge Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
