# Generated by Django 5.2.17 on 2026-08-16 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_adminauditlog_domainmergelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(db_index=True, help_text="User's original topic name (e.g. 'Python Development'). Preserved forever.", max_length=200)),
                ('original_description', models.TextField(blank=True, default='')),
                ('joined_via', models.CharField(choices=[('CREATED', 'Created by User'), ('MERGED', 'Merged with Community'), ('DISCOVERED', 'Discovered'), ('ENROLLED', 'Enrolled'), ('ADMIN_ASSIGNED', 'Admin Assigned')], default='ENROLLED', max_length=30)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private (Only Me)'), ('COMMUNITY', 'Community Members'), ('PUBLIC', 'Public on Portfolio'), ('UNLISTED', 'Unlisted')], default='COMMUNITY', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'In Progress / Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Calculated percentage (0-100%)')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('custom_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community_domain', models.ForeignKey(blank=True, help_text='Canonical community domain link. Null if private custom topic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_enrollments', to='domains.communitydomain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Domain',
                'verbose_name_plural': 'User Domains',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('community_domain__isnull', False), ('status', 'ACTIVE')), fields=('user', 'community_domain'), name='unique_active_user_community_domain')],
            },
        ),
    ]
