# Generated by Django 5.2.17 on 2026-08-16 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_trigram_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in curriculum roadmap')),
                ('estimated_hours', models.PositiveIntegerField(default=6, help_text='Estimated learning hours')),
                ('is_core', models.BooleanField(default=True, help_text='Part of core canonical curriculum')),
                ('is_approved', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='domains.communitydomain')),
            ],
            options={
                'verbose_name': 'Curriculum Topic',
                'verbose_name_plural': 'Curriculum Topics',
                'ordering': ['order', 'title'],
                'unique_together': {('domain', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to=settings.AUTH_USER_MODEL)),
                ('user_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_plans', to='domains.userdomain')),
            ],
            options={
                'verbose_name': 'Learning Plan',
                'verbose_name_plural': 'Learning Plans',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='domains.curriculumtopic')),
            ],
            options={
                'verbose_name': 'Topic Milestone',
                'verbose_name_plural': 'Topic Milestones',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningPlanTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], default='NOT_STARTED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_topics', to='domains.learningplan')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='domains.curriculumtopic')),
            ],
            options={
                'verbose_name': 'Learning Plan Topic',
                'verbose_name_plural': 'Learning Plan Topics',
                'ordering': ['order', 'id'],
                'unique_together': {('plan', 'topic')},
            },
        ),
    ]
